image: node:7.5

cache:
  paths:
  - node_modules/

stages:
  - test

test_app:
  stage: test
  script:
    - git config --global url."https://github.com/".insteadOf git@github.com:
    - git config --global url."https://".insteadOf git://
    - npm install
    - grunt jshint
    - karma start karma.conf.js
  tags:
  - docker
