# Image automatically built from GitHub repo:
#   https://github.com/charman/docker-node-phantomjs
image: charman/docker-node-phantomjs

cache:
  paths:
  - node_modules/

stages:
  - test

test_app:
  stage: test
  script:
    # Force git to use https to work around JHU firewall settings,
    # as recommended here:
    #   https://github.com/npm/npm/issues/5257
    - 'git config --global url."https://github.com/".insteadOf git@github.com:'
    - 'git config --global url."https://".insteadOf git://'
    - npm install
    - node_modules/grunt/bin/grunt jshint
    - node_modules/karma/bin/karma start karma.conf.js
  tags:
  - docker
